version: "3.9"

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: "tomdev"
      POSTGRES_PASSWORD: "tomdev"
      POSTGRES_DB: "db"
    ports:
      - "5432:5432"

  nats:
    image: nats-streaming
    ports:
      - "4222:4222"
      - "8222:8222"
